[project]
name = "enotaryo-qr-reader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.115.11",
    "opencv-python>=4.11.0.86",
    "pillow>=11.1.0",
]
